### ISSUE TITLE
[Suggestion] Run the same event as the leader does

### ISSUE THREAD

**Issue by ghost** [pretendlake/Parties#7]
There has been some issues with my server when I click an npc to join the game. The leader gets into the game but the party members get tp into a different world and suppose they are not part of the game. Can you any chance run the same event instead of teleporting players to a different world?

**Comment by jasonw4331** [comment]
You say run the event, but it's not the parties plugin which runs the event in the first place. It is your npc plugin.
You would need custom code to have the npc plugin run it for all the party members. Something like an interaction handler as a go-between for the plugins.

**Comment by ghost** [comment]
Ok thanks I can try doing that.
